### ISSUE TITLE
vit does not respect "inverse" color from .taskrc

### ISSUE THREAD

**Issue by divagant-martian** [vit-project/vit#184] opened 2019-06-07 05:15 UTC
add `color.active=inverse` to your `.taskrc`
start a task (in vit or not, does not matter)
the task is shown with inverted colors in your terminal, while vit shows them unchanged

**Comment by scottkosty** [comment] 2019-06-07 05:33
@zombiefungus Thanks for this report. What is your version of vit?

**Comment by divagant-martian** [comment] 2019-06-07 13:44
Hi, thanks for the fast reply
```bash
$ vit --version
1.3
```

**Comment by thehunmonkgroup** [comment] 2019-06-07 21:43
This is also an issue in VIT 2.x.

I've investigated further, and don't see any reasonable way emulate the behavior, so have removed support for that attribute in 2.x. -- if someone figures out how to do it, a pull request is welcome.

For a pretty easy workaround, have a look at the caveat posted here, which should work for both VIT 1.x/2.x: https://github.com/scottkosty/vit/blob/2.x/COLOR.md#caveats

**Comment by divagant-martian** [comment] 2019-06-07 22:03
Thanks, I've looked into your workaround but at least in this case it does not fix the problem, since the `inverse` is applied to a state (active). 

Take for example a rule that makes a task red when it is overdue, and another that makes it green if it is due today. There is no way to convey both bits of info (if the task is active + overdue vs active + due today vs ...) having a rule that presets the foreground and background color.

But in any case thanks for the response, and for this awesome tool

**Comment by thehunmonkgroup** [comment] 2019-06-07 22:06
VIT 2.x doesn't blend colors, so does not suffer from this issue. See https://github.com/scottkosty/vit/blob/2.x/COLOR.md#vit-task-coloring

**Comment by scottkosty** [comment] 2019-06-08 04:24
@zombiefungus if you are up for it and test VIT 2.x, let us know how it goes.

**Comment by divagant-martian** [comment] 2019-06-08 15:30
Hi, just installed vit 2.x, first thing I can notice, is that "inverse" is not ignored, but actually makes vit crash. I'll get back after exploring a bit further

**Comment by divagant-martian** [comment] 2019-06-08 16:27
Hi, now I get what you mean by "2.x does not suffer from this". It is possible now to show more info per row using colors. 

I find it a bit hard to get the clue of what matters from single columns, but colorizing the description via 
other rules would do the trick for me. Is this possible? Let' say, description using the color of overdue, etc?

Regarding this issue, I think it could be closed with a won't fix (?)

**Comment by thehunmonkgroup** [comment] 2019-06-08 20:53
Crash in inverse color config was fixed in https://github.com/scottkosty/vit/commit/f593d198a6b3040351b3583d2c15db3e2a58353d and will be in the alpha 2 release.

It's highly unlikely I'll add any additional coloring indicators, or do any refactoring in that department -- it was quite a heavy lift to get the current coloring architecture working well.

I would advise reviewing https://github.com/scottkosty/vit/blob/2.x/COLOR.md#vit-task-coloring, learning more about the marker feature, and giving yourself some time to adjust to the more subtle coloring cues.

**Closed as completed by thehunmonkgroup** 2019-06-08 20:53 UTC
Labels: won't fix

**Comment by wavexx** [comment] 2020-11-17 14:32
I don't want to report a new issue regarding a 'wontfix', so I'm commenting on this one.

I understand the cause of not supporting inverse, but I don't really want to change taskwarrior's settings either.

Can I simply override the color in vit? It's unclear if this is possible.

I don't care if some/all colors don't match, since the color usage is not strictly identical between the two anyway. I'd rather have a completely different color scheme than compromise my current settings.

**Comment by thehunmonkgroup** [comment] 2020-11-17 18:15
I would consider a PR that allows color overrides, if it was clean and didn't complicate the code, but will probably not invest the time myself to write it.

**Comment by wavexx** [comment] 2020-11-17 22:59
Should we log a feature request for this maybe?
Can't put my force on this one (yet), but sounds something that could be helped by some visibility.

**Comment by thehunmonkgroup** [comment] 2020-11-18 05:16
Feature requests are always welcome, and PRs are even more so :)
