### ISSUE TITLE
Exception when trying to run vit

### ISSUE THREAD

**Issue by ddeimeke** [vit-project/vit#204] opened 2019-09-29 08:51 UTC
```
[dirk@crest:~] $ virtualenv --python=python3 venv/vit
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/dirk/venv/vit/bin/python3
Also creating executable in /home/dirk/venv/vit/bin/python
Installing setuptools, pip, wheel...done.

[dirk@crest:~] 3s $ source /home/dirk/venv/vit/bin/activate

[dirk@crest:~] [vit] $ pip install vit
Collecting vit
  Downloading https://files.pythonhosted.org/packages/a2/3c/6fcec8310bf4de982db65b635aab10ed0b99b005ef8805f2974e0a86d76c/vit-2.0.0-py3-none-any.whl (90kB)
     |████████████████████████████████| 92kB 3.5MB/s 
Collecting tzlocal (from vit)
  Downloading https://files.pythonhosted.org/packages/ef/99/53bd1ac9349262f59c1c421d8fcc2559ae8a5eeffed9202684756b648d33/tzlocal-2.0.0-py2.py3-none-any.whl
Collecting tasklib (from vit)
  Downloading https://files.pythonhosted.org/packages/d3/bd/5b51b9bea5955a7ba44db2385ec63da0bdcd9ec0ed7e32ac55d127f32a82/tasklib-1.2.1.tar.gz
Collecting urwid (from vit)
  Downloading https://files.pythonhosted.org/packages/c7/90/415728875c230fafd13d118512bde3184d810d7bf798a631abc05fac09d0/urwid-2.0.1.tar.gz (604kB)
     |████████████████████████████████| 614kB 13.5MB/s 
Collecting pytz (from vit)
  Downloading https://files.pythonhosted.org/packages/87/76/46d697698a143e05f77bec5a526bf4e56a0be61d63425b68f4ba553b51f2/pytz-2019.2-py2.py3-none-any.whl (508kB)
     |████████████████████████████████| 512kB 47.6MB/s 
Collecting six>=1.4 (from tasklib->vit)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Building wheels for collected packages: tasklib, urwid
  Building wheel for tasklib (setup.py) ... done
  Created wheel for tasklib: filename=tasklib-1.2.1-cp37-none-any.whl size=25044 sha256=c78a114fa8a487b389429cdba3219e921ed4137dda4ea83b036058a37e08fc63
  Stored in directory: /home/dirk/.cache/pip/wheels/31/b4/3c/0cecbf79075ad987e23706d426c59a93437fc05fabf817ac3c
  Building wheel for urwid (setup.py) ... done
  Created wheel for urwid: filename=urwid-2.0.1-cp37-cp37m-linux_x86_64.whl size=248906 sha256=71cf11ee83bfb17fc1990e76bbc3006c0ece6f68dad5848725de396888837149
  Stored in directory: /home/dirk/.cache/pip/wheels/34/06/50/24011714e101b5ad8518c69175d117a257413e3c15a92983f0
Successfully built tasklib urwid
Installing collected packages: pytz, tzlocal, six, tasklib, urwid, vit
Successfully installed pytz-2019.2 six-1.12.0 tasklib-1.2.1 tzlocal-2.0.0 urwid-2.0.1 vit-2.0.0

[dirk@crest:~] [vit] 3s $ vit
/home/dirk/.vit/config.ini doesn't exist, create? (y/n): y

/home/dirk/.vit/config.ini created. This is the default user configuration file. 

It is heavily commented with explanations and lists the default values for all available user configuration variables. Check it out!

Press enter to continue...
Traceback (most recent call last):
  File "/home/dirk/venv/vit/bin/vit", line 10, in <module>
    sys.exit(main())
  File "/home/dirk/venv/vit/lib/python3.7/site-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "/home/dirk/venv/vit/lib/python3.7/site-packages/vit/application.py", line 70, in __init__
    self.load_early_config()
  File "/home/dirk/venv/vit/lib/python3.7/site-packages/vit/application.py", line 79, in load_early_config
    self.reports = self.task_config.get_reports()
  File "/home/dirk/venv/vit/lib/python3.7/site-packages/vit/config_parser.py", line 336, in get_reports
    self.reports[report_name] = self.rectify_report(report_name, report)
  File "/home/dirk/venv/vit/lib/python3.7/site-packages/vit/config_parser.py", line 340, in rectify_report
    report['subproject_indentable'] = self.has_project_column(report_name) and self.has_primary_project_ascending_sort(report)
  File "/home/dirk/venv/vit/lib/python3.7/site-packages/vit/config_parser.py", line 344, in has_project_column
    return self.get_column_index(report_name, 'project') is not None
  File "/home/dirk/venv/vit/lib/python3.7/site-packages/vit/config_parser.py", line 351, in get_column_index
    return self.reports[report_name]['columns'].index(column) if column in self.reports[report_name]['columns'] else None
KeyError: 'columns'
```

Operating system is Fedora 30, Taskwarrior is built from source.

```
[dirk@crest:~] [vit] $ task diagnostics

task 2.5.2
   Platform: Linux

Compiler
    Version: 9.2.1 20190827 (Red Hat 9.2.1-1)
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++14

Build Features
      Built: Sep  7 2019 08:37:36
     Commit: e186d375d
      CMake: 3.14.5
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.6.8
 Build type: release

Configuration
       File: /home/dirk/.taskrc (found), 3178 bytes, mode 100664
       Data: /home/dirk/.task (found), dir, mode 40775
    Locking: Enabled
         GC: Enabled
    $EDITOR: vim
     Server: pales.myown-it.com:53589
         CA: ~/.task/ca.cert.pem, readable, 3714 bytes
Certificate: ~/.task/Dirk_Deimeke.cert.pem, readable, 3724 bytes
        Key: ~/.task/Dirk_Deimeke.key.pem, readable, 24742 bytes
      Trust: strict
    Ciphers: NORMAL
      Creds: My own IT/Dirk Deimeke/************************************

Hooks
     System: Enabled
   Location: /home/dirk/.task/hooks
             (-none-)

Tests
   Terminal: 132x36
       Dups: Scanned 7465 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 7465 tasks for broken references:
             No broken references found
```

**Comment by thehunmonkgroup** [comment] 2019-09-29 14:35
This issue was reported in https://github.com/scottkosty/vit/pull/192, but I didn't get any more information from that reporter to properly debug it. I still fail to see how a report can't have any columns.

From the output you posted, it looks like you haven't made any customizations to ```config.ini```, correct? If that's the case, then VIT uses the ```next``` report by default, which *definitely* should have columns.

I'd like to see the output of ```task _show | grep report.next``` from that custom build of TaskWarrior.

Finally, TaskWarrior 2.5.2 is unreleased -- there may be some bugs and/or breaking changes in it. I'd recommend building an official TaskWarrior release to see if that fixes the issue.

**Comment by thehunmonkgroup** [comment] 2019-09-29 15:40
Closing as a duplicate of https://github.com/scottkosty/vit/pull/192, the issue has been confirmed, and the patch supplied there does fix the issue, but I need more info from the TaskWarrior maintainer to implement a proper fix.

For now, roll back to a stable version of TaskWarrior, or use the current patch supplied at https://github.com/scottkosty/vit/pull/192

**Closed as completed by thehunmonkgroup** 2019-09-29 15:40 UTC
