### ISSUE TITLE
project name "status" not working

### ISSUE THREAD

**Issue by baszoetekouw** [vit-project/vit#15] opened 2017-06-13 12:22 UTC
When I try to reassign a task to a project named "status", its project is instead set to "Pending".  

When editing the task, changingg its project works fine.

**Comment by scottkosty** [comment] 2017-06-25 05:30
I confirm this behavior, but I'm not sure if this is a bug. VIT runs the following command:

    task <ID> modify 'proj:status'

(off-topic: I think we should not use that abbreviation, in case a user has the Taskwarrior config variable abbreviation.minimum set to a value higher than 4).

That command seems reasonable to me. I think this might be a feature. For example, I often do the following:

    task 19 modify scheduled:due-2days

to refer to the due date of scheduled. Now, it's pretty strange to think that the user actually would want to assign a project name to be whatever the status of that bug is, but I think Taskwarrior here allows that flexibility.

**Comment by scottkosty** [comment] 2017-06-25 05:46
> (off-topic: I think we should not use that abbreviation, in case a user has the Taskwarrior config variable abbreviation.minimum set to a value higher than 4).

I fixed this at 4c87dfbc.

**Comment by scottkosty** [comment] 2017-06-25 18:47
I've been thinking about this, and it would be nice if VIT allowed for two workflows:

1. The input is parsed by Taskwarrior (which is currently the case).
2. The input is quoted.

The user should be able to choose the default mode, and also be able to easily toggle in-between them in a prompt. The mode should be indicated somehow on the VIT screen.

What do you think about such a feature?

**Comment by fdela** [comment] 2020-07-28 22:21
This bug should probably be closed as it's working as designed in TaskWarrior (_project:status_ vs _project:'status'_).

@scottkosty Wouldn't it be best if you put your proposal in a separate, feature request issue, so the discussion can happen there, in a more discoverable place?

**Comment by scottkosty** [comment] 2020-07-31 18:25
@fdela Good idea. Let's close this. I will make a note in my "maybe-someday" file to hopefully come back to this feature sometime (maybe in a few years). If you are interested in the feature, or anyone else, please open an issue. I don't do it now because I currently don't have time even for follow-up discussion.

**Comment by scottkosty** [comment] 2020-07-31 18:25
@fdela by the way, I tried to send you an email. Did you by chance receive it? If not, could you please send me an email (it should be easy to find)? Thanks.

**Closed** 2020-07-31 18:25 UTC
