### ISSUE TITLE
pip install from repository/directory fails

### ISSUE THREAD

**Issue by nblock** [vit-project/vit#181] opened 2019-05-28 10:45 UTC
A fresh install from the repository (`pip install git+https://github.com/scottkosty/vit.git@2.x`) or from a local checkout (`pip install .`) fails:

```
Collecting git+https://github.com/scottkosty/vit.git@2.x
  Cloning https://github.com/scottkosty/vit.git (to revision 2.x) to /tmp/pip-req-build-_32miw36
Branch '2.x' set up to track remote branch '2.x' from 'origin'.
Switched to a new branch '2.x'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-_32miw36/setup.py", line 4, in <module>
        from vit import version
      File "/tmp/pip-req-build-_32miw36/vit/__init__.py", line 2, in <module>
        from .application import Application
      File "/tmp/pip-req-build-_32miw36/vit/application.py", line 14, in <module>
        import urwid
    ModuleNotFoundError: No module named 'urwid'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-_32miw36/
```

* vit: 5b71e2e1c4f050b540b22867e1210c71e1964ac6
* Python: 3.7.3 (via pyenv)

**Comment by thehunmonkgroup** [comment] 2019-05-28 16:08
I can reproduce this error, but must admit I'm stumped as to why.

urwid is listed as a dependency in ```requirements.txt```, and I specifically read that file in and pass it to ```install_requires``` in ```setup.py```: https://github.com/scottkosty/vit/blob/2.x/setup.py#L6-L18

That's the suggested approach from this SO post: https://stackoverflow.com/questions/36963563/pip-wont-install-my-packages-dependencies

So any ideas welcome.

For the local checkout via ```pip install .```, running ```pip install -r requirements.txt``` first is an easy workaround

The instructions at [DEVELOPMENT.md](https://github.com/scottkosty/vit/blob/2.x/DEVELOPMENT.md) also work.

**Comment by nblock** [comment] 2019-05-28 16:51
A wild guess: the issue is with https://github.com/scottkosty/vit/blob/2.x/setup.py#L4 as it executes `vit/__init__.py` and there, `vit.application.Application` is imported. The file `vit/application.py` contains the `import urwid` line.

Nothing important, I just stumbled over it while playing with 2.x.

**Comment by thehunmonkgroup** [comment] 2019-05-28 17:02
Ah yes, I think you're right about that. I was trying to be clever about centralizing the version info. Looks like I'll need to parse that file manually instead of importing it.

**Comment by thehunmonkgroup** [comment] 2019-05-28 20:33
Should be fixed by https://github.com/scottkosty/vit/commit/b6966ce09f58e4fb06ebce8fdc6e4caeeb1387f0

Can you verify?

**Comment by nblock** [comment] 2019-05-29 07:12
Successfully installed a fresh venv via:
```pip install git+https://github.com/scottkosty/vit@b6966ce09f58e4fb06ebce8fdc6e4caeeb1387f0```

**Closed as completed** 2019-05-30 15:16 UTC
