### ISSUE TITLE
vit does not start correctly when task is upgraded to version 2.5.3

### ISSUE THREAD

**Issue by donnex** [vit-project/vit#286] opened 2021-02-20 14:08 UTC
**Describe the bug**

task / taskwarrior 2.5.3 seems to break the current `vit` release. At least on my machine with task installed from Arch pacman repositories.

I'm not sure what introduced this. 2.5.2 was a big release with a lot of changes.

Traceback when starting `vit`

```
  File ".../vit/config_parser.py", line 351, in get_column_index
    return self.reports[report_name]['columns'].index(column) if column in self.reports[report_name]['columns'] else None
KeyError: 'columns'
```
After some digging around it seems that some new (?) report shows up in the new task release and it does not have columns defined.

`timesheet` is the name of the report.

```
 'timesheet': {'filter': ['(',
                          '+PENDING',
                          'and',
                          'start.after:now-4wks',
                          ')',
                          'or',
                          '(',
                          '+COMPLETED',
                          'and',
                          'end.after:now-4wks',
                          ')'],
               'name': 'timesheet',
               'subproject_indentable': False}}
```

When changing line `351` in `config_parser.py` to handle this everything seems fine. I'm not sure if this is the correct solution but that's seems to be the problem.

```
return self.reports[report_name]['columns'].index(column) if 'columns' in self.reports[report_name] and column in self.reports[report_name]['columns'] else None
```

**To Reproduce**

- Install task 2.5.3 (possibly 2.5.2 as well)
- Start `vit`

**Expected behavior**

- `vit` should start as normal

**Comment by thehunmonkgroup** [comment] 2021-02-20 16:04
Duplicate of https://github.com/vit-project/vit/pull/192

Install the beta or dev version, a new VIT point release will hopefully happen soon.

**Comment by bsberry** [comment] 2021-02-24 18:01
Checked out the 2.X branch from source. Locally running task@2.5.3. Still seeing the error.

```
[benb@benb-mbp] (2.x) ~/bin/vit
$ python --version
Python 3.9.2
[benb@benb-mbp] (2.x) ~/bin/vit
$ git rev-parse HEAD
8fdebc30ef3e2cd3d48bad894fb0c15e7f611856
[benb@benb-mbp] (2.x) ~/bin/vit
$ python ./vit/command_line.py
Traceback (most recent call last):
  File "/Users/benb/bin/vit/./vit/command_line.py", line 8, in <module>
    main()
  File "/Users/benb/bin/vit/./vit/command_line.py", line 5, in main
    Application(options, filters)
  File "/usr/local/lib/python3.9/site-packages/vit/application.py", line 70, in __init__
    self.load_early_config()
  File "/usr/local/lib/python3.9/site-packages/vit/application.py", line 79, in load_early_config
    self.reports = self.task_config.get_reports()
  File "/usr/local/lib/python3.9/site-packages/vit/config_parser.py", line 336, in get_reports
    self.reports[report_name] = self.rectify_report(report_name, report)
  File "/usr/local/lib/python3.9/site-packages/vit/config_parser.py", line 340, in rectify_report
    report['subproject_indentable'] = self.has_project_column(report_name) and self.has_primary_project_ascending_sort(report)
  File "/usr/local/lib/python3.9/site-packages/vit/config_parser.py", line 344, in has_project_column
    return self.get_column_index(report_name, 'project') is not None
  File "/usr/local/lib/python3.9/site-packages/vit/config_parser.py", line 351, in get_column_index
    return self.reports[report_name]['columns'].index(column) if column in self.reports[report_name]['columns'] else None
KeyError: 'columns'
```

Appreciate the time. `vit` is awesome.

**Closed as completed** 2021-02-24 20:28 UTC
Labels: duplicate
