### ISSUE TITLE
wrong date displayed

### ISSUE THREAD

**Issue by alexjwilliams** [vit-project/vit#345] opened 2023-09-13 21:42 UTC
The date inside the task's `.task` file is `2023-09-13 17:00:00`. The date displayed with `:all` inside `vit` is `2023-09-14`, while the date displayed by `task all` on the command line is `2023-09-13`. Changing the datetime to `2023-09-13 16:59:00` causes the date to be correctly displayed in `vit`. My timezone (as displayed by `date`) is `PDT`. I am running ubuntu 23.04 inside a docker container.

**Comment by thehunmonkgroup** [comment] 2023-09-13 22:37
If you can use https://github.com/vit-project/vit/blob/2.x/scripts/generate-dummy-install.sh as a starting point, and post a modified version here that allows me to reproduce the issue, I can have a look. I have not had any issues with dates displaying correctly.

**Comment by alexjwilliams** [comment] 2023-09-13 23:54
`dockerfile`:
```
FROM docker.io/ubuntu:23.04

RUN apt-get update && apt-get install -y wget taskwarrior vit vim

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y tzdata

RUN wget https://raw.githubusercontent.com/vit-project/vit/2.x/scripts/generate-dummy-install.sh && chmod +x generate-dummy-install.sh
```

`set-up-container.sh`:
```
#!/usr/bin/bash 
docker build -f dockerfile -t taskwarrior .

docker run -v /etc/timezone:/etc/timezone:ro \
	   -v /etc/localtime:/etc/localtime:ro \
	   --name taskwarrior \
	   -dit \
	   taskwarrior:latest

docker attach taskwarrior

docker stop taskwarrior

docker rm taskwarrior
```

Steps to reproduce:

1. Modify task 2 to have due date `2023-09-13 17:00:00`.
2. Run `:all`

**Comment by thehunmonkgroup** [comment] 2023-09-15 01:16
I'm confused by all the Docker commands -- https://github.com/vit-project/vit/blob/2.x/scripts/generate-dummy-install.sh already creates an isolated Vit install in /tmp -- is there some reason you believe the Docker stuff is neccessary?

**Comment by alexjwilliams** [comment] 2023-09-15 05:16
I am using taskwarrior inside a docker container and I want to use vit inside the container as well. For this reason, and because the error could possibly be due to the container’s date/time settings, I set up a minimal environment to demonstrate the issue that I am seeing. If you put dockerfile and set-up-container.sh into the same directory and run the later, you will build the container and be dropped into a shell. When you exit, the container will be stopped and deleted. The -v options mount those paths to the container in a read only fashion and are necessary to get the date/time inside the container to match that of the host. -dit launches the container in a “detached” and “interactive” mode, with a tty inside.

**Comment by thehunmonkgroup** [comment] 2023-09-15 13:42
Debugging a Docker issue is out of scope. I am unable to reproduce your issue with a fresh install:

![2023-09-15_09-38](https://github.com/vit-project/vit/assets/43772/9eb4a3ec-a74b-4756-a7e1-096c0da6cadb)

![2023-09-15_09-39](https://github.com/vit-project/vit/assets/43772/dc7e7385-80bc-4754-b429-6df43011bb0e)

If you find an issue in the code itself, I'm more than happy to investigate and try to fix. Looks to be working properly in a clean install as far as I can tell. You may also want to check your `.taskrc` for settings that might be causing the issue.

**Comment by alexjwilliams** [comment] 2023-09-17 01:33
tasklib is the source of the issue. The datetimes in the `Task` objects don't match the datetimes in the `.task` files.

**Comment by thehunmonkgroup** [comment] 2023-09-17 15:31
Excellent catch! If you haven't already, I'd recommend filing an issue over there -- that project is generally pretty responsive.

**Closed as completed by thehunmonkgroup** 2023-09-17 15:31 UTC
